#!/bin/bash
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=slc7_amd64_gcc820
eval `scramv1 project CMSSW CMSSW_10_6_5`
cd CMSSW_10_6_5/src
eval `scramv1 runtime -sh`
cmsenv
cp ${_CONDOR_SCRATCH_DIR}/* .


tar -zxvf include.tar.gz



