/// \file
/// \ingroup tutorial_tree
/// \notebook -nodraw
/// Example of Root macro to copy a subset of a Tree to a new Tree, selecting entries.
///
/// Only selected entries are copied to the new Tree.
/// The input file has been generated by the program in `$ROOTSYS/test/Event`
/// with `Event 1000 1 99 1`
///
/// \macro_code
///
/// \author Rene Brun


void extract_cat() {

   //Get old file, old tree and set top branch address
   TFile *oldfile;
   TString dir = "out.root";
   gSystem->ExpandPathName(dir);
   TTree *oldtree = (TTree*)oldfile->Get("Events");
   Long64_t nentries = oldtree->GetEntries();
   //Event *cat   = 0;
   string cat="";
   //oldtree->SetBranchAddress("cat",&cat);
   oldtree->SetBranchStatus("*",1);
   cout<<" how many "<<nentries<<endl;

   //Create a new file + a clone of old tree in new file
   TFile *newfile = new TFile("small.root","recreate");
   TTree *newtree = oldtree->CloneTree(0);

   for (Long64_t i=0;i<nentries; i++) {
      oldtree->GetEntry(i);
      //if (cat== "mmmt") 
      newtree->Fill();
   }
   newtree->Print();
   newtree->AutoSave();
   delete oldfile;
   delete newfile;
}
